version: '3.8'

services:
  mysql-svc:
    container_name: mysql-svc
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=anim
      - MYSQL_PASSWORD=1234
    
  api:
    container_name: api
    image: animshamura/los-be
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=anim
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=mysql-svc
      - MYSQL_PORT=3306

  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always

  client: 
    container_name: client
    image: animshamura/los-fe
    restart: always

